apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-node-configmap-deployment-1
  name: my-node-configmap-deployment-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-configmap-deployment-1-frontend
  template:
    metadata:
      labels:
        app: my-node-configmap-deployment-1-frontend
    spec:
      volumes:
        - name: html
          emptyDir: {}
        - name: app-config-volumes
          configMap:
              name: app-settings
      containers:
        - name: my-node-pod-1-frontend
          image: srivamshikanth/example-docker-app-1:latest
          env:
            - name: ENVVAR
              valueFrom:
                configMapKeyRef:
                  name: app-settings
                  key: enemies
            - name: TITLE
              value: " Node Deployment"
            - name: HAPPY
          volumeMounts:
            - mountPath: /app/html
              name: html
              readOnly: true
            - name: app-config-volumes
              mountPath: /app/config
          resources:
            limits:
              memory: "128Mi" #128MB
              cpu: "200m"
        - name: my-node-pod-2-frontend
          image: alpine
          command: ["/bin/sh","-c"]
          args:
            - while true; do date >> /html/index.html; sleep 5; done
          volumeMounts:
            - mountPath: /html
              name: html
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"

