apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-08-27T18:13:47Z"
  generation: 1
  labels:
    app: my-nginx-deployment-1
  name: my-nginx-deployment-1
  namespace: default
  resourceVersion: "230213"
  selfLink: /apis/apps/v1/namespaces/default/deployments/my-nginx-deployment-1
  uid: 7a9d3d16-ae3f-4560-96b0-905af17cf4c5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-nginx-deployment-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx-deployment-1
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 9080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
