apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-1
  labels:
    app: nginx
    rel: stable

spec:
  containers:
    - name: my-nginx-1
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          port: 80
          path: /index.html
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
