apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-08-28T16:36:17Z"
  labels:
    app: example-service-clusterip-1
  name: example-service-clusterip-1
  namespace: default
  resourceVersion: "269008"
  selfLink: /api/v1/namespaces/default/services/example-service-1
  uid: 6206d28e-9e33-4e44-be41-b5ceca49bf13
spec:
  clusterIP: 10.101.234.76
  ports:
  - name: 30001-80
    port: 30001
    protocol: TCP
    targetPort: 80
  selector:
    app: my-node-deployment-1-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
