apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-08-28T16:36:17Z"
  labels:
    app: example-service-loadbalancer-1
  name: example-service-loadbalancer-1
  namespace: default
  resourceVersion: "269008"
  selfLink: /api/v1/namespaces/default/services/example-service-1
  uid: 6206d28e-9e33-4e44-be41-b5ceca49bf13
spec:
  #clusterIP: 10.101.234.76
  ports:
  - name: "30001-9080"
    port: 80 # will  be a 80 port for a type loadbalancer & will goto 9080 port
    protocol: TCP
    targetPort: 9080 # will  be a 80 port for a type loadbalancer
  selector:
    app: my-node-deployment-1-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
